# Set the theme
theme: jekyll-theme-minimal

# Set the site's title and description
title: Age of Wonder Curated Dataset
description: The Age of Wonder Curated Dataset is a resource for taught post-graduate courses developed by the Department of Health Sciences at the University of York in collaboration with Bradford Teaching Hospitals NHS Foundation Trust.
